config/routes.rb
Rails.application.routes.draw do
  
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :accounts, controllers: {
    sessions: 'admin/sessions'
  }, only: [:sessions]
  
  namespace :admin do
  
    root to: 'mains#home'
    mount Ckeditor::Engine => '/ckeditor'

    resource :main, only: %i() do
      collection do
        get :home
      end
    end

    resources :articles do
      member do
        post :reedit
        post :push_art_to_six
        post :push_art_to_wp
      end
    end

    resources :csv_files, only: %i(index new create destroy) do
      collection do
        post :extract
      end
    end

    resources :resources do
      member do
        post :reedit
      end
      collection do
        post :deduplication
      end
    end

  end

end

app/models/account.rb
class Account < ApplicationRecord
  devise :database_authenticatable, :rememberable, :trackable, :validatable
  has_many :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def errors_full_messages_text
    errors.full_messages.join('，')
  end
end

app/models/article.rb
class Article < ApplicationRecord
  paginates_per 10

  include AASM
  extend Enumerize

  # belongs_to :resource
  belongs_to :account

  include ArticleCategoriesAble

  PUSH_STATUS_HASH = {pushed: 1, waiting: 0}

  enumerize :six_status, in: PUSH_STATUS_HASH, default: :waiting, predicates: true, scope: true, i18n_scope: "activerecord.attributes.article/push_status"
  enumerize :wp_status, in: PUSH_STATUS_HASH, default: :waiting, predicates: true, scope: true, i18n_scope: "activerecord.attributes.article/push_status"


  def push_art_to_six

    return true if six_status.pushed?

    response = ArtApi::Api.push_six_art(six_art_params)
    body = JSON.parse response.body
    if response.code == 200 and body["status"].to_i == 200     
      self.update!(six_status: PUSH_STATUS_HASH[:pushed])
    end
    true
  end

  def push_art_to_wp
    PinYin.abbr(record.name, false, false)
  end



  private

  def six_art_params
    filename = PinYin.abbr(title, false, false)
    {
      title: title,
      seo_title: seo_title,
      keywords: keywords,
      description: description,
      filename: filename,
      content: content,
      cat_id: six_category_id,
      release: 0,
    }
  end
  



end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, mount_on: :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/models/csv_file.rb
require 'csv'
class CsvFile < ApplicationRecord
    mount_uploader :name, CsvUploader
    extend Enumerize

    include AASM

    STATUS_HASH = {pending: 3, finished: 2, fails: 1}

    enumerize :status, in: STATUS_HASH, default: :pending, predicates: true, scope: true, i18n_scope: "activerecord.attributes.csv_file/status"

    include CsvFileExtractAble


    def self.statuses
        STATUS_HASH.with_indifferent_access
    end
    
    aasm :status, column: :status, enum: true do
        state :pending, initial: true
        state :finished
        state :fails

        event :successful_extracted  do
          transitions from: :pending, to: :finished
        end

        event :failure_extracted  do
            transitions from: :pending, to: :fails
        end
    end



end

app/models/medium.rb
class Medium < ApplicationRecord
end

app/models/resource.rb
class Resource < ApplicationRecord
  paginates_per 10

  include AASM
  extend Enumerize

  # has_one :article

  STATUS_HASH = {pending: 3, finished: 2, fails: 1}

  enumerize :status, in: STATUS_HASH, default: :pending, predicates: true, scope: true, i18n_scope: "activerecord.attributes.resource/status"


  def self.statuses
    STATUS_HASH.with_indifferent_access
  end
  
  aasm :status, column: :status, enum: true do
    state :pending, initial: true
    state :finished
    state :fails

    event :successful_extracted  do
      transitions from: :pending, to: :finished
    end

    event :failure_extracted  do
      transitions from: :pending, to: :fails
    end
  end


  def reedit
    resource_id = "resource_id_#{self.id}"

    data = Rails.cache.read(resource_id)

    if data.blank?
      response = CatAi::Api.reedit(mode=1, self.content)
      data = {code: response.code, content: response.body}
      Rails.cache.write(resource_id, data, expires_in: 5.minutes)
    end

    unless data[:code] == 200
      failure_extracted!
      return self
    end

    ActiveRecord::Base.transaction do
      begin       
        Article.create!(title: self.title, content: data[:content])
        successful_extracted!
      rescue => e        
        failure_extracted!
        raise ActiveRecord::Rollback
      end
    end

    self
  end

  def self.deduplication    
    
    total_count = 0

    while true
      ids = select("MAX(id) as id, count(*) as count").group(:title).having('count>1').collect(&:id)
      if ids.size == 0
        break;
      end
      where(id: ids).destroy_all
      total_count += ids.size
    end
    total_count
  end
  


end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < Admin::BaseController
  before_action :set_article, only: [:edit, :update, :show, :destroy, :reedit, :push_art_to_six, :push_art_to_wp]

  def index
    @q = current_account.articles.ransack(params[:q])
    @articles = @q.result.page(params[:page])
  end

  def new
    @article = article_chain.new
  end

  def show
  end

  def create
    @article = article_chain.new(article_params)

    if @article.save
      redirect_to admin_article_path(@article)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
      redirect_to admin_article_path(@article)
    else
      render :edit
    end
  end

  def destroy
    if @article.destroy
        flash[:notice] = t(:destroy_success)
    else
        flash[:error] = @article.errors_full_messages_text
    end
    redirect_to action: :index
  end

  def reedit
    unless @article.pending?
      render json: {status: @article.status_text}
      return
    end

    @article = @article.reedit

    render json: {status: @article.status_text}
    
  end




  def push_art_to_six
    begin
      render json: {msg: 'success'} if @article.push_art_to_six
    rescue => e        
      render json: {msg: 'fails', info: e.inspect}
    end

  end

  def push_art_to_wp
    sleep 2
    render json: {msg: 'success'}
  end



  private

  def article_chain
    current_account.articles
  end

  def set_article
    @article = article_chain.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :content, :six_category_id, :wp_category_id, :seo_title, :description, :keywords)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/media_controller.rb
class MediaController < ApplicationController
  def search
    @q = Medium.ransack(params[:q])
    @medium = @q.result.page(params[:page]).per(50)        
  end
end

app/controllers/systems_controller.rb
class SystemsController < ApplicationController
end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/helpers/admin/base_helper.rb
module Admin::BaseHelper
    
    # 根据路径获取所链接的标题，或目标页面的标题
    def path_title(path=nil)
        hash = {}
        if path
        hash = Rails.application.routes.recognize_path(path)
        end
        hash[:controller] ||= controller_path
        hash[:action] ||= action_name
        I18n.t( "#{hash[:controller].gsub("/", ".")}.#{hash[:action]}.title" )
    end


    def is_active(controller_name, paths)
        'active' if paths.include?(controller_name)
    end

end

app/helpers/admin/csv_files_helper.rb
module Admin::CsvFilesHelper
end

app/helpers/admin/documents_helper.rb
module Admin::DocumentsHelper
end

app/helpers/admin/mains_helper.rb
module Admin::MainsHelper
end

app/helpers/admin/resources_helper.rb
module Admin::ResourcesHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/media_helper.rb
module MediaHelper
end

app/helpers/systems_helper.rb
module SystemsHelper
end

app/views/admin/articles/_form.html.erb
<%= simple_form_for [:admin, @article] do |f| %>
  <div class="box-body">          
      <div class="form-group">
        <%= f.input :title, input_html: {class: "form-control"} %>
      </div>
      <div class="form-group">
        <%= f.input :seo_title, input_html: {class: "form-control"} %>
      </div>
      <div class="form-group">
        <%= f.input :keywords, input_html: {class: "form-control"} %>
      </div>
      <div class="form-group">
        <%= f.input :description, input_html: {class: "form-control"} %>
      </div>
      <div class="form-group">
        <%= f.input :six_category_id, as: :select,  collection: Article.categories["six"], selected: @article.six_category_id, input_html: {class: "form-control"} %>
      </div>
      <div class="form-group">
        <%= f.input :wp_category_id, as: :select,  collection: Article.categories["wp"], selected: @article.wp_category_id, input_html: {class: "form-control"} %>
      </div>
      
      <div class="form-group">
        <%= f.input :content, as: :ckeditor, input_html: { ckeditor: { toolbar: 'Full', language: 'zh-CN', height: 600 }} %>
      </div>

  </div>

  
  <div class="box-footer">
    <%= f.button :submit, class: 'btn btn-warning' %>
  </div>
<% end %>

app/views/admin/articles/index.html.erb
<!-- Main content -->
<section class="content">
    <div class="row">
    <div class="col-xs-12">
        <div class="box">
        <div class="box-header">
            <h3 class="box-title"><%= link_to('添加文章', new_admin_article_path, class: 'btn btn-sm btn-warning')%></h3>
            
        <span class="box-title">
        <%= search_form_for @q, url: [:admin, :articles],html: {class: "form-inline search"}  do |f| %>
        <i class="fa fa-telegram"></i>
        <%= f.select :six_status_eq, Article.six_status.values.map { |v| [v.text, v.value] }, {}, {class: 'form-control'}  %>
        <i class="fa fa-wordpress"></i>
        <%= f.select :wp_status_eq, Article.wp_status.values.map { |v| [v.text, v.value] }, {}, {class: 'form-control'}  %>

        <%= f.search_field :title_cont, class: 'form-control', placeholder: "标题内容" %>

        <%= f.button "检索", class: 'btn btn-warning'%>
        <% end %>
        </span>



        </div><!-- /.box-header -->
        <div class="box-body">
            <table id="example2" class="table table-bordered table-hover">
            <thead>
                <tr>
                <th>ID</th>
                <th>标题</th>
                <th><i class="fa fa-telegram"></i></th>
                <th><i class="fa fa-wordpress"></i></th>
                <th>上传时间</th>

                <th>操作</th>
                </tr>
            </thead>

            <tbody>
                <% @articles.each do |article| %>
                    <tr>
                        <td><%= article.id %></td>
                        <td><%= article.title %></td>
       
                        <td id="six_status_<%= article.id%>"><%= article.six_status_text %></td>
                        <td id="wp_status_<%= article.id%>"><%= article.wp_status_text %></td>
 
                        <td><%= article.created_at.localtime.to_s(:db) %></td>
                        <td>
                            <%= link_to('查看', admin_article_path(article), class: 'btn btn-sm btn-warning', data: {id: article.id}) %>
                                 
              
                            <%= link_to('修改', edit_admin_article_path(article), class: 'btn btn-sm btn-warning', )%>
                            <%= link_to('删除', admin_article_path(article), class: 'btn btn-sm btn-warning', method: 'delete')%>
                        </td>
 
                    </tr>
                    
                <%end%>
                
            </tbody>
            </table>
            <%= paginate @articles, class: "pagination pagination-sm no-margin" %>
        </div><!-- /.box-body -->
        </div><!-- /.box -->

    </div><!-- /.col -->
    </div><!-- /.row -->
</section><!-- /.content -->


<script>
$('.reedit_content').on('ajax:beforeSend', function() {
  $(this).html('<i class="fa fa-refresh fa-spin"></i> 处理中')
});

$('.reedit_content').on('ajax:success', function(event) {
    [data, status, xhr] = event.detail
    
    id = $(this).data('id')
    $('#status_'+ id).html(data.status)
});



$('.reedit_content').on('ajax:complete', function(ex,e) {
    $(this).html('重写')
});
</script>


        
        

app/views/admin/articles/new.html.erb
<!-- Main content -->
<section class="content">
    <div class="row">
    <div class="col-xs-12">
        <div class="box">
        <div class="box-header">
            <h3 class="box-title">基础信息</h3>
        </div><!-- /.box-header -->
        <div class="box-body">

<%= render 'form' %>

        </div><!-- /.box-body -->
        </div><!-- /.box -->

    </div><!-- /.col -->
    </div><!-- /.row -->
</section><!-- /.content -->

app/views/admin/articles/show.html.erb
<!-- Main content -->
<section class="content">
    <div class="row">
    <div class="col-xs-12">
        <div class="box">
        <div class="box-header">
            <h3 class="box-title">基础信息</h3>
        </div><!-- /.box-header -->
        <div class="box-body">
            <table id="example2" class="table table-bordered table-hover">
            <tbody>

            
                    
                    <tr>
                        <th style="width: 15%"><%= t(@article.class.human_attribute_name(:title))%></th>
                        <td><%= @article.title %></td>   
                    </tr>

                    <tr>
                        <th style="width: 15%"><%= t(@article.class.human_attribute_name(:seo_title))%></th>
                        <td><%= @article.seo_title %></td>   
                    </tr>

                    <tr>
                        <th style="width: 15%"><%= t(@article.class.human_attribute_name(:keywords))%></th>
                        <td><%= @article.keywords.split(',').join(" ") if @article.keywords %></td>   
                    </tr>

                    <tr>
                        <th style="width: 15%"><%= t(@article.class.human_attribute_name(:description))%></th>
                        <td><%= @article.description %></td>   
                    </tr>

                    <tr>
                        <th style="width: 15%"><%= t(@article.class.human_attribute_name(:six_category_id))%></th>
                        <td>
                        <%= select_tag "six_category_id", options_for_select(Article.categories["six"], @article.six_category_id), class: "form-control", disabled: true, style: "width: 100px" %>
                        </td>   
                    </tr>

                    <tr>
                        <th style="width: 15%"><%= t(@article.class.human_attribute_name(:wp_category_id))%></th>
                        <td>
                        <%= select_tag "wp_category_id", options_for_select(Article.categories["wp"], @article.wp_category_id), class: "form-control", disabled: true, style: "width: 100px" %>
                        </td>   
                    </tr>

                    <tr>
                        <th style="width: 15%"><%= t(@article.class.human_attribute_name(:content))%></th>
                        <td><%= raw @article.content %></td>   
                    </tr>

                    <tr>
                        <th style="width: 15%"><%= t(@article.class.human_attribute_name(:six_status))%></th>
                        <td class="six_status">
                        <%= @article.six_status_text%>
                        
                        <% if @article.six_status.waiting? %>
                            &nbsp;&nbsp;&nbsp;&nbsp;
                            <%= link_to('推送', push_art_to_six_admin_article_path(@article), class: 'push_art btn btn-sm btn-default', data: {class: '.six_status'},  method: 'post', remote: true)%>
                        <%end%>
                        </td>    
                    </tr> 

                    <tr>
                        <th style="width: 15%"><%= t(@article.class.human_attribute_name(:wp_status))%></th>
                        <td class="wp_status">
                        <%= @article.wp_status_text%>
                        
                        <% if @article.wp_status.waiting? %>
                            &nbsp;&nbsp;&nbsp;&nbsp;
                            <%= link_to('推送', push_art_to_wp_admin_article_path(@article), class: 'push_art btn btn-sm btn-default', data: {class: '.wp_status'},  method: 'post', remote: true)%>
                        <%end%>
                        </td>    
                    </tr> 

                 <tr>
                    <td colspan="2" align="center">
                        <%= link_to('修改', edit_admin_article_path(@article), class: 'btn btn-sm btn-warning' )%>
                    </td>
                </tr>
            
                

            </tbody>
            </table>
        
        </div><!-- /.box-body -->
        </div><!-- /.box -->



     





    </div><!-- /.col -->
    </div><!-- /.row -->
</section><!-- /.content -->

<%= render '/shared/admin/modal' %>

<script>
$('.push_art').on('ajax:beforeSend', function() {
  $(this).html('<i class="fa fa-refresh fa-spin"></i> 推送中')
});

$('.push_art').on('ajax:success', function(event) {
    [data, status, xhr] = event.detail
    
    console.log(data.msg)
    class_status= $(this).data('class')
    if (data.msg == 'success'){
        console.log(class_status)
        $(class_status).html('已推送')
        $(".modal-body").html('推送成功')
        $(".modal").modal();
       
    }
});


</script>




        
        