config/routes.rb
Rails.application.routes.draw do
  
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :accounts, controllers: {
    sessions: 'admin/sessions'
  }, only: [:sessions]
  
  namespace :admin do
  
    root to: 'mains#home'
    mount Ckeditor::Engine => '/ckeditor'

    resource :main, only: %i() do
      collection do
        get :home
      end
    end

    resources :articles do
      member do
        post :reedit
        post :push_art_to_six
        post :push_art_to_wp
      end
    end

    resources :csv_files, only: %i(index new create destroy) do
      collection do
        post :extract
      end
    end

    resources :resources do
      member do
        post :reedit
      end
      collection do
        post :deduplication
      end
    end

  end

end

app/models/account.rb
class Account < ApplicationRecord
  devise :database_authenticatable, :rememberable, :trackable, :validatable
  has_many :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def errors_full_messages_text
    errors.full_messages.join('，')
  end
end

app/models/article.rb
class Article < ApplicationRecord
  paginates_per 10

  include AASM
  extend Enumerize

  # belongs_to :resource
  belongs_to :account

  include ArticleCategoriesAble

  PUSH_STATUS_HASH = {pushed: 1, waiting: 0}

  enumerize :six_status, in: PUSH_STATUS_HASH, default: :waiting, predicates: true, scope: true, i18n_scope: "activerecord.attributes.article/push_status"
  enumerize :wp_status, in: PUSH_STATUS_HASH, default: :waiting, predicates: true, scope: true, i18n_scope: "activerecord.attributes.article/push_status"


  def push_art_to_six

    return true if six_status.pushed?

    response = ArtApi::Api.push_six_art(six_art_params)
    body = JSON.parse response.body
    if response.code == 200 and body["status"].to_i == 200     
      self.update!(six_status: PUSH_STATUS_HASH[:pushed])
    end
    true
  end

  def push_art_to_wp
    PinYin.abbr(record.name, false, false)
  end



  private

  def six_art_params
    filename = PinYin.abbr(title, false, false)
    {
      title: title,
      seo_title: seo_title,
      keywords: keywords,
      description: description,
      filename: filename,
      content: content,
      cat_id: six_category_id,
      release: 0,
    }
  end
  



end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/models/csv_file.rb
require 'csv'
class CsvFile < ApplicationRecord
    mount_uploader :name, CsvUploader
    extend Enumerize

    include AASM

    STATUS_HASH = {pending: 3, finished: 2, fails: 1}

    enumerize :status, in: STATUS_HASH, default: :pending, predicates: true, scope: true, i18n_scope: "activerecord.attributes.csv_file/status"

    include CsvFileExtractAble


    def self.statuses
        STATUS_HASH.with_indifferent_access
    end
    
    aasm :status, column: :status, enum: true do
        state :pending, initial: true
        state :finished
        state :fails

        event :successful_extracted  do
          transitions from: :pending, to: :finished
        end

        event :failure_extracted  do
            transitions from: :pending, to: :fails
        end
    end



end

app/models/medium.rb
class Medium < ApplicationRecord
end

app/models/resource.rb
class Resource < ApplicationRecord
  paginates_per 10

  include AASM
  extend Enumerize

  # has_one :article

  STATUS_HASH = {pending: 3, finished: 2, fails: 1}

  enumerize :status, in: STATUS_HASH, default: :pending, predicates: true, scope: true, i18n_scope: "activerecord.attributes.resource/status"


  def self.statuses
    STATUS_HASH.with_indifferent_access
  end
  
  aasm :status, column: :status, enum: true do
    state :pending, initial: true
    state :finished
    state :fails

    event :successful_extracted  do
      transitions from: :pending, to: :finished
    end

    event :failure_extracted  do
      transitions from: :pending, to: :fails
    end
  end


  def reedit
    resource_id = "resource_id_#{self.id}"

    data = Rails.cache.read(resource_id)

    if data.blank?
      response = CatAi::Api.reedit(mode=1, self.content)
      data = {code: response.code, content: response.body}
      Rails.cache.write(resource_id, data, expires_in: 5.minutes)
    end

    unless data[:code] == 200
      failure_extracted!
      return self
    end

    ActiveRecord::Base.transaction do
      begin       
        Article.create!(title: self.title, content: data[:content])
        successful_extracted!
      rescue => e        
        failure_extracted!
        raise ActiveRecord::Rollback
      end
    end

    self
  end

  def self.deduplication    
    
    total_count = 0

    while true
      ids = select("MAX(id) as id, count(*) as count").group(:title).having('count>1').collect(&:id)
      if ids.size == 0
        break;
      end
      where(id: ids).destroy_all
      total_count += ids.size
    end
    total_count
  end
  


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/media_controller.rb
class MediaController < ApplicationController
  def search
    @q = Medium.ransack(params[:q])
    @medium = @q.result.page(params[:page]).per(50)        
  end
end

app/controllers/systems_controller.rb
class SystemsController < ApplicationController
end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/helpers/admin/base_helper.rb
module Admin::BaseHelper
    
    # 根据路径获取所链接的标题，或目标页面的标题
    def path_title(path=nil)
        hash = {}
        if path
        hash = Rails.application.routes.recognize_path(path)
        end
        hash[:controller] ||= controller_path
        hash[:action] ||= action_name
        I18n.t( "#{hash[:controller].gsub("/", ".")}.#{hash[:action]}.title" )
    end


    def is_active(controller_name, paths)
        'active' if paths.include?(controller_name)
    end

end

app/helpers/admin/csv_files_helper.rb
module Admin::CsvFilesHelper
end

app/helpers/admin/documents_helper.rb
module Admin::DocumentsHelper
end

app/helpers/admin/mains_helper.rb
module Admin::MainsHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/media_helper.rb
module MediaHelper
end

app/helpers/systems_helper.rb
module SystemsHelper
end

app/views/admin/resources/_form.html.erb
<%= simple_form_for [:admin, @resource] do |f| %>
  <div class="box-body">          
      <div class="form-group">
        <%= f.input :title, input_html: {class: "form-control"} %>
      </div>

      <div class="form-group">
        <%= f.input :content, as: :ckeditor, input_html: { ckeditor: { toolbar: 'Full', language: 'zh-CN', height: 600 }} %>
      </div>
      <div class="form-group">
        <%= f.input :status, as: :select,  collection: Resource.status.values.map { |v| [v.text, v.value] }, selected: @resource.status_value, input_html: {class: "form-control"} %>
      </div>
  </div>

  
  <div class="box-footer">
    <%= f.button :submit, class: 'btn btn-warning' %>
  </div>
<% end %>

app/views/admin/resources/edit.html.erb
<!-- Main content -->
<section class="content">
    <div class="row">
    <div class="col-xs-12">
        <div class="box">
        <div class="box-header">
            <h3 class="box-title">基础信息</h3>
        </div><!-- /.box-header -->
        <div class="box-body">
        
        <%= render 'form' %>

        </div><!-- /.box-body -->
        </div><!-- /.box -->

    </div><!-- /.col -->
    </div><!-- /.row -->
</section><!-- /.content -->

app/views/admin/resources/index.html.erb
<!-- Main content -->
<section class="content">
    <div class="row">
    <div class="col-xs-12">
        <div class="box">
        <div class="box-header">
            <h3 class="box-title">
              <%= link_to('添加文章', new_admin_resource_path, class: 'btn btn-sm btn-warning')%>
              <%= link_to('去重标题', deduplication_admin_resources_path, class: 'deduplication btn btn-sm btn-warning', method: 'post', remote: true) %>
            </h3>

        <span class="box-title">
        <%= search_form_for @q, url: [:admin, :resources],html: {class: "form-inline search"}  do |f| %>
  
        <%= f.select :status_eq, Resource.status.values.map { |v| [v.text, v.value] }, {}, {class: 'form-control'}  %>
        
        <%= f.search_field :title_cont, class: 'form-control', placeholder: "标题内容" %>

        <%= f.button "检索", class: 'btn btn-warning'%>
        <% end %>
        </span>




        </div><!-- /.box-header -->
        <div class="box-body">
            <table id="example2" class="table table-bordered table-hover">
            <thead>
                <tr>
                <th>ID</th>
                <th>标题</th>
                <th>状态</th>
                <th>上传时间</th>

                <th>操作</th>
                </tr>
            </thead>
            <tbody>
                <% @resources.each do |resource| %>
                    <tr>
                        <td><%= resource.id %></td>
                        <td><%= link_to(resource.title, edit_admin_resource_path(resource)) %></td>

                        <td id="status_<%= resource.id%>"><%= resource.status_text %></td>
                        <td><%= resource.created_at.localtime.to_s(:db) %></td>
                        <td>
                            <%= link_to('重写', reedit_admin_resource_path(resource), class: 'reedit_content btn btn-sm btn-warning', data: {id: resource.id},  method: 'post', remote: true) %>
                                 
              
                            <%= link_to('修改', edit_admin_resource_path(resource), class: 'btn btn-sm btn-warning', )%>
                            <%= link_to('删除', admin_resource_path(resource), class: 'btn btn-sm btn-warning', method: 'delete')%>
                        </td>
 
                    </tr>
                    
                <%end%>
                
            </tbody>
            </table>
            <%= paginate @resources, class: "pagination pagination-sm no-margin" %>
            &nbsp;&nbsp; 总计：<%= @resources.total_count%> 条
        </div><!-- /.box-body -->
        </div><!-- /.box -->

    </div><!-- /.col -->
    </div><!-- /.row -->
</section><!-- /.content -->

<%= render '/shared/admin/modal' %>

<script>
$('.reedit_content').on('ajax:beforeSend', function() {
  $(this).html('<i class="fa fa-refresh fa-spin"></i> 处理中')
});

$('.reedit_content').on('ajax:success', function(event) {
    [data, status, xhr] = event.detail
    
    id = $(this).data('id')
    $('#status_'+ id).html(data.status)
    $(".modal-body").html(text)
    $(".modal").modal();
});



$('.reedit_content').on('ajax:complete', function(ex,e) {
    $(this).html('重写')
});
</script>






<script>
$('.deduplication').on('ajax:beforeSend', function() {
  $(this).html('<i class="fa fa-refresh fa-spin"></i> 去重中')
});

$('.deduplication').on('ajax:success', function(event) {
    [data, status, xhr] = event.detail
    if (data.msg == 'success'){
        text = "处理完毕，共处理"+ data.total_count + "条"
        $(".modal-body").html(text)
        $(".modal").modal();
       
    }
});
$('.deduplication').on('ajax:complete', function(ex,e) {
    $(this).html('去重标题')
});
</script>


        
        

app/views/admin/resources/new.html.erb
<!-- Main content -->
<section class="content">
    <div class="row">
    <div class="col-xs-12">
        <div class="box">
        <div class="box-header">
            <h3 class="box-title">基础信息</h3>
        </div><!-- /.box-header -->
        <div class="box-body">
        
        <%= render 'form' %>

        </div><!-- /.box-body -->
        </div><!-- /.box -->

    </div><!-- /.col -->
    </div><!-- /.row -->
</section><!-- /.content -->

app/views/admin/resources/show.html.erb
<!-- Main content -->
<section class="content">
    <div class="row">
    <div class="col-xs-12">
        <div class="box">
        <div class="box-header">
            <h3 class="box-title">基础信息</h3>
        </div><!-- /.box-header -->
        <div class="box-body">
            <table id="example2" class="table table-bordered table-hover">
            <tbody>

            
                    
                    <tr>
                        <th style="width: 15%"><%= t(@resource.class.human_attribute_name(:title))%></th>
                        <td><%= @resource.title %></td>   
                    </tr>

                    <tr>
                        <th style="width: 15%"><%= t(@resource.class.human_attribute_name(:content))%></th>
                        <td><%= @resource.content %></td>   
                    </tr>
   
                    <tr>
                        <th style="width: 15%"><%= t(@resource.class.human_attribute_name(:status))%></th>
                        <td><%= @resource.status_text %></td>    
                    </tr> 

                 <tr>
                    <td colspan="2" align="center">
                        <%= link_to('修改', edit_admin_resource_path(@resource), class: 'btn btn-sm btn-warning')%>
                    </td>
                </tr>
            
                

            </tbody>
            </table>
        </div><!-- /.box-body -->
        </div><!-- /.box -->



     





    </div><!-- /.col -->
    </div><!-- /.row -->
</section><!-- /.content -->





        
        

app/views/layouts/admin/admin.html.erb
<%= render '/shared/admin/head' %>

<%= content_for(:content) do %>
  <% if account_signed_in? %>
    <%= render 'shared/admin/navbar/signed' %>
  <% else %>
    <%= render 'shared/admin/navbar/unsigned' %>
  <% end %>
      <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">

    <!-- Flash -->
    <div class="row">
    <div class="col-sm-12">
        <%= render 'shared/admin/flash' %>
    </div>
    </div>
    <section class="content-header">
      <h1>
          <% if content_for?(:path_title) %>
            <%= yield(:path_title) %>
          <% else %>
            <%= path_title %>
          <% end %>
      </h1>
      <ol class="breadcrumb">
        <%=  render_breadcrumbs(tag: :li, separator: ' > ') %>
      </ol>
      

    </section>

    <%= yield %>
  </div>

<% end%>

<%= render '/shared/admin/footer' %>

<%= render template: "layouts/admin/base" %>

app/views/layouts/admin/base.html.erb
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <title>Art </title>

    <meta name="keywords" content="cpa">
    <meta name="description" content="cpa">

    <!--[if lt IE 8]>
    <meta http-equiv="refresh" content="0;ie.html" />
    <![endif]-->

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="shortcut icon" href="favicon.ico">
    <%= stylesheet_link_tag    'admin', media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <%= javascript_include_tag 'admin', 'data-turbolinks-track': 'reload' %>

    <%= yield(:head) %>
</head>


  <body class="hold-transition sidebar-mini skin-yellow-light expansion-alids-init" style="height: auto; min-height: 100%;">
    <div class="wrapper">
    <%= yield(:content) %>
    </div>
  </body>
</html>

app/views/layouts/admin/login.html.erb
<!DOCTYPE html>
<html>
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    

    <title>资料库-登录</title>
    <meta name="keywords" content="资料库-登录">
    <meta name="description" content="资料库-登录">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="shortcut icon" href="favicon.ico"> 

    <%= stylesheet_link_tag    'admin', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'admin', 'data-turbolinks-track': 'reload' %>

    <link href="/dist/css/animate.min.css" rel="stylesheet">
    <link href="/dist/css/style.min.css?v=4.0.0" rel="stylesheet">

    <script>if(window.top !== window.self){ window.top.location = window.location;}</script>
</head>

<body class="gray-bg">

    <div class="middle-box text-center loginscreen  animated fadeInDown">
        <div>
            <div>
                <h1 class="logo-name">Art</h1>
            </div>
            <h3>欢迎使用</h3>

            <div class="row">
            <div class="col-sm-12">
                <%= render 'shared/admin/flash' %>
            </div>
            </div>
            <%= yield %>
        </div>
    </div>

</body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Magazine</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/admin/_error_messages.html.erb
<% if target && target.errors.any? %>
 <div class="alert alert-block alert-danger">
   <a class="close" data-dismiss='alert' href="#">×</a>
   <p><%= fa_icon("warning", text: "有 #{target.errors.count} 处问题导致无法提交:") %></p>
   <ul>
   <% target.errors.full_messages.each do |msg| %>
     <li><%= msg %></li>
   <% end %>
   </ul>
 </div>
<% end %>

app/views/shared/admin/_flash.html.erb
<% if flash[:alert] %>
  <div class="alert alert-danger alert-dismissible fade in" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
    <%= flash[:alert] %>
  </div>
<% end %>

<% if flash[:notice] %>
  <div class="alert alert-success alert-dismissible fade in" role="success">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
    <%= flash[:notice] %>
  </div>
<% end %>

app/views/shared/admin/_footer.html.erb
<%= content_for(:content) do %>
    <footer class="main-footer">
      <div class="pull-right hidden-xs">
        <b>Version</b> 1.0.0
      </div>
      <strong>Copyright &copy; 2018 <a href="http://www.bestpv.cn">苏州微光网络科技有限公司</a>.</strong> All rights reserved.
    </footer>
    <!-- jQuery UI 1.11.4 -->

    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <!-- AdminLTE App -->
    <script src="/dist/js/adminlte.js?time=<%= Time.now.to_i%>"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="/dist/js/demo.js"></script>
<% end %>

app/views/shared/admin/_head.html.erb
<%= content_for(:head) do %>
    <link rel="stylesheet" href="/dist/css/AdminLTE.min.css">
    <link rel="stylesheet" href="/dist/css/skins/skin-yellow-light.min.css">
<%end %>

app/views/shared/admin/_modal.html.erb
<div class="modal" >
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title">操作状态</h4>
            </div>
            <div class="modal-body">
                操作成功
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">确定</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/shared/admin/_panel.html.erb
<div class="panel panel-default">
  <% if title %>
    <div class="panel-heading">
      <%= title %>
    </div>
  <% end %>
  <%= content %>
</div>

app/views/shared/admin/_panel_body.html.erb
<div class="panel-body">
  <%= content %>
</div>

app/views/shared/admin/_panel_footer.html.erb
<div class="panel-footer">
    <%= content %>
</div>

app/views/shared/admin/_table_empty.html.erb
<div class="table-empty text-center">
  <%= fa_icon("search 5x") %>
  <h4><%= local_assigns[:text] || "查找不到相关记录" %></h4>
</div>


<%#可以附带block%>

<%#<div class="table-empty text-center">%>
<%#  <%= fa_icon("search 5x") +|%>
<%#  <h4>查找不到相关记录</h4>%>
<%#  <%= yield +|%>
<%#</div>%>
<%#<%= render layout: "shared/admin/table_empty" do +|%>
<%#  <h1>TEST</h1>%>
<%#<% end +|%>

app/views/shared/admin/navbar/_signed.html.erb
    <header class="main-header">
        <!-- Logo -->
        <a href="" class="logo">
          <!-- mini logo for sidebar mini 50x50 pixels -->
          <span class="logo-mini">Art</span>
          <!-- logo for regular state and mobile devices -->
          <span class="logo-lg"><b>Art</b></span>
        </a>
        
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top">
          <!-- Sidebar toggle button-->
          <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <li><a href="javascript:void(0);"><%= current_account.email %></a></li>
                <li><%= link_to '安全退出', [:destroy, :account, :session], method: "delete" %></li>
            </ul>
          </div>
        </nav>
      </header>
      <!-- Left side column. contains the logo and sidebar -->
      <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
          <!-- Sidebar user panel -->


          <!-- sidebar menu: : style can be found in sidebar.less -->
          <ul class="sidebar-menu" data-widget="tree">

            <%= active_link_to admin_root_path, wrap_tag: :li do %>
              <i class="fa fa-home"></i><span> 首页</span>
            <%end%>

              <%= active_link_to admin_articles_path, wrap_tag: :li do %>
                <i class="fa fa-file-archive-o"></i><span> 文章管理</span>
              <%end%>
  
      


           

              <%= active_link_to admin_resources_path, wrap_tag: :li do %>
                <i class="fa fa-file-zip-o"></i><span> 资源管理</span>
              <%end%>

              <%= active_link_to admin_csv_files_path, wrap_tag: :li do %>
                <i class="fa fa-file-zip-o"></i><span> 文档管理</span>
              <%end%>
      

            

           </ul>
        </section>
        <!-- /.sidebar -->
      </aside>