config/routes.rb
Rails.application.routes.draw do
  
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :accounts, controllers: {
    sessions: 'admin/sessions'
  }, only: [:sessions]
  
  namespace :admin do
  
    root to: 'mains#home'
    mount Ckeditor::Engine => '/ckeditor'

    resource :main, only: %i() do
      collection do
        get :home
      end
    end

    resources :articles do
      member do
        post :reedit
        post :push_art_to_six
        post :push_art_to_wp
      end
    end

    resources :csv_files, only: %i(index new create destroy) do
      collection do
        post :extract
      end
    end

    resources :resources do
      member do
        post :reedit
      end
      collection do
        post :deduplication
      end
    end

  end

end

app/models/account.rb
class Account < ApplicationRecord
  devise :database_authenticatable, :rememberable, :trackable, :validatable
  has_many :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def errors_full_messages_text
    errors.full_messages.join('，')
  end
end

app/models/article.rb
class Article < ApplicationRecord
  paginates_per 10

  include AASM
  extend Enumerize

  # belongs_to :resource
  belongs_to :account

  include ArticleCategoriesAble

  PUSH_STATUS_HASH = {pushed: 1, waiting: 0}

  enumerize :six_status, in: PUSH_STATUS_HASH, default: :waiting, predicates: true, scope: true, i18n_scope: "activerecord.attributes.article/push_status"
  enumerize :wp_status, in: PUSH_STATUS_HASH, default: :waiting, predicates: true, scope: true, i18n_scope: "activerecord.attributes.article/push_status"


  def push_art_to_six

    return true if six_status.pushed?

    response = ArtApi::Api.push_six_art(six_art_params)
    body = JSON.parse response.body
    if response.code == 200 and body["status"].to_i == 200     
      self.update!(six_status: PUSH_STATUS_HASH[:pushed])
    end
    true
  end

  def push_art_to_wp
    PinYin.abbr(record.name, false, false)
  end



  private

  def six_art_params
    filename = PinYin.abbr(title, false, false)
    {
      title: title,
      seo_title: seo_title,
      keywords: keywords,
      description: description,
      filename: filename,
      content: content,
      cat_id: six_category_id,
      release: 0,
    }
  end
  



end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, mount_on: :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/models/csv_file.rb
require 'csv'
class CsvFile < ApplicationRecord
    mount_uploader :name, CsvUploader
    extend Enumerize

    include AASM

    STATUS_HASH = {pending: 3, finished: 2, fails: 1}

    enumerize :status, in: STATUS_HASH, default: :pending, predicates: true, scope: true, i18n_scope: "activerecord.attributes.csv_file/status"

    include CsvFileExtractAble


    def self.statuses
        STATUS_HASH.with_indifferent_access
    end
    
    aasm :status, column: :status, enum: true do
        state :pending, initial: true
        state :finished
        state :fails

        event :successful_extracted  do
          transitions from: :pending, to: :finished
        end

        event :failure_extracted  do
            transitions from: :pending, to: :fails
        end
    end



end

app/models/medium.rb
class Medium < ApplicationRecord
end

app/models/resource.rb
class Resource < ApplicationRecord
  paginates_per 10

  include AASM
  extend Enumerize

  # has_one :article

  STATUS_HASH = {pending: 3, finished: 2, fails: 1}

  enumerize :status, in: STATUS_HASH, default: :pending, predicates: true, scope: true, i18n_scope: "activerecord.attributes.resource/status"


  def self.statuses
    STATUS_HASH.with_indifferent_access
  end
  
  aasm :status, column: :status, enum: true do
    state :pending, initial: true
    state :finished
    state :fails

    event :successful_extracted  do
      transitions from: :pending, to: :finished
    end

    event :failure_extracted  do
      transitions from: :pending, to: :fails
    end
  end


  def reedit
    resource_id = "resource_id_#{self.id}"

    data = Rails.cache.read(resource_id)

    if data.blank?
      response = CatAi::Api.reedit(mode=1, self.content)
      data = {code: response.code, content: response.body}
      Rails.cache.write(resource_id, data, expires_in: 5.minutes)
    end

    unless data[:code] == 200
      failure_extracted!
      return self
    end

    ActiveRecord::Base.transaction do
      begin       
        Article.create!(title: self.title, content: data[:content])
        successful_extracted!
      rescue => e        
        failure_extracted!
        raise ActiveRecord::Rollback
      end
    end

    self
  end

  def self.deduplication    
    
    total_count = 0

    while true
      ids = select("MAX(id) as id, count(*) as count").group(:title).having('count>1').collect(&:id)
      if ids.size == 0
        break;
      end
      where(id: ids).destroy_all
      total_count += ids.size
    end
    total_count
  end
  


end

app/controllers/admin/csv_files_controller.rb
class Admin::CsvFilesController < Admin::BaseController
    before_action :set_csv_file, only: [:edit, :update, :show, :destroy]

    def index
        @csv_files = CsvFile.page(params[:page])
    end
    
    def new
        @csv_file = CsvFile.new
    end

    def create
        @csv_file = CsvFile.new(csv_file_params)
  
        if @csv_file.save
          flash[:notice] = t(:operation_success)
          redirect_to admin_csv_files_path
        else
          render :new
        end
    end


    def destroy
        if @csv_file.destroy
            flash[:notice] = t(:destroy_success)
        else
            flash[:error] = @csv_file.errors_full_messages_text
        end
        redirect_to action: :index
    end

    def extract
      begin       
        CsvFile.extract_content_to_resources
        render json: {msg: 'success'}
      rescue => e   
        render json: {msg: 'fails', info: e.inspect}
      end

    end

    private

    def set_csv_file
        @csv_file = CsvFile.find(params[:id])
    end

    def csv_file_params
        params.require(:csv_file).permit(:name)
    end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/media_controller.rb
class MediaController < ApplicationController
  def search
    @q = Medium.ransack(params[:q])
    @medium = @q.result.page(params[:page]).per(50)        
  end
end

app/controllers/systems_controller.rb
class SystemsController < ApplicationController
end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/helpers/admin/base_helper.rb
module Admin::BaseHelper
    
    # 根据路径获取所链接的标题，或目标页面的标题
    def path_title(path=nil)
        hash = {}
        if path
        hash = Rails.application.routes.recognize_path(path)
        end
        hash[:controller] ||= controller_path
        hash[:action] ||= action_name
        I18n.t( "#{hash[:controller].gsub("/", ".")}.#{hash[:action]}.title" )
    end


    def is_active(controller_name, paths)
        'active' if paths.include?(controller_name)
    end

end

app/helpers/admin/csv_files_helper.rb
module Admin::CsvFilesHelper
end

app/helpers/admin/documents_helper.rb
module Admin::DocumentsHelper
end

app/helpers/admin/mains_helper.rb
module Admin::MainsHelper
end

app/helpers/admin/resources_helper.rb
module Admin::ResourcesHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/media_helper.rb
module MediaHelper
end

app/helpers/systems_helper.rb
module SystemsHelper
end

app/views/admin/csv_files/_form.html.erb
<%= simple_form_for [:admin, @csv_file] do |f| %>
  <div class="box-body">          
    <div class="form-group">
      <%= f.input :name, as: :file %>                  
    </div>
  </div> 
  <div class="box-footer">
    <%= f.button :submit, class: 'btn btn-warning' %>
  </div> 
<% end %>

app/views/admin/csv_files/index.html.erb
<!-- Main content -->
<section class="content">
    <div class="row">
    <div class="col-xs-12">
        <div class="box">
        <div class="box-header">
            <h3 class="box-title"><%= link_to('添加CSV', new_admin_csv_file_path, class: 'btn btn-sm btn-warning')%></h3>
            <h3 class="box-title"><%= link_to('批量处理内容', extract_admin_csv_files_path, class: 'extract btn btn-sm btn-success', method: :post, remote: true)%></h3>
        </div><!-- /.box-header -->
        <div class="box-body">
            <table id="example2" class="table table-bordered table-hover">
            <thead>
                <tr>
                <th>名称</th>
                <th>状态</th>
                <th>上传时间</th>
                <th>更新时间</th>
                <th>操作</th>
                </tr>
            </thead>
            <tbody>
                <% @csv_files.each do |csv_file| %>
                    <tr>
                        <td><%= csv_file.name_identifier %></td>
                        <td><%= csv_file.status_text %></td>
                        <td><%= csv_file.created_at.localtime.to_s(:db) %></td>
                        <td><%= csv_file.updated_at.localtime.to_s(:db) %></td>
                        <td>
                            
                            <%= link_to('删除', admin_csv_file_path(csv_file), class: 'btn btn-sm btn-warning', method: 'delete')%>
                        </td>
 
                    </tr>
                    
                <%end%>
                
            </tbody>
            </table>
            <%= paginate @csv_files %>
        </div><!-- /.box-body -->
        </div><!-- /.box -->

    </div><!-- /.col -->
    </div><!-- /.row -->
</section><!-- /.content -->

<%= render '/shared/admin/modal' %>

<script>
$('.extract').on('ajax:beforeSend', function() {
  $(this).html('<i class="fa fa-refresh fa-spin"></i> 处理中')
});

$('.extract').on('ajax:success', function(event) {
    [data, status, xhr] = event.detail
    if (data.msg == 'success'){
        text = "处理完毕"
        $(".modal-body").html(text)
        $(".modal").modal();
       
    }
});

$('.extract').on('ajax:complete', function(ex,e) {
    $(this).html('批量处理内容')
});

</script>


        
        

app/views/admin/csv_files/new.html.erb
<!-- Main content -->
<section class="content">
    <div class="row">
    <div class="col-xs-12">
        <div class="box">
        <div class="box-header">
            <h3 class="box-title">基础信息</h3>
        </div><!-- /.box-header -->
        <div class="box-body">

            <%= render 'form' %>

        </div><!-- /.box-body -->
        </div><!-- /.box -->

    </div><!-- /.col -->
    </div><!-- /.row -->
</section><!-- /.content -->